#!/bin/bash
set -e

run-daemon() {
    if [[ `docker ps|grep ghdld|wc -l` = 0 ]]; then
        echo running container daemon...
        docker run --rm -it -d -v `pwd`:`pwd` -w `pwd` -u 1000:1000 --name ghdld ghdl/ext sleep 1h >/dev/null
        echo daemon is up
    fi
}

main() {
    run-daemon

    docker exec -w $PWD ghdld python3 vunit-main.py pdp11.$TEST --minimal --keep-compiling --gtkwave-fmt vcd -o out
}

if [[ "$1" = "" ]]; then
    TEST='*'
else
    TEST="$1.*"
fi


main

