mem load -skip 0 -filltype value -filldata XXXX -fillradix hexadecimal /main/ram/data
mem load -filltype value -filldata 13C0 -fillradix hexadecimal /main/ram/data(0)
mem load -filltype value -filldata 00013 -fillradix hexadecimal /main/ram/data(1)
mem load -filltype value -filldata 13C3 -fillradix hexadecimal /main/ram/data(2)
mem load -filltype value -filldata 0014 -fillradix hexadecimal /main/ram/data(3)
mem load -filltype value -filldata 12CF -fillradix hexadecimal /main/ram/data(4)
mem load -filltype value -filldata 0012 -fillradix hexadecimal /main/ram/data(5)
mem load -filltype value -filldata F100 -fillradix hexadecimal /main/ram/data(6)
mem load -filltype value -filldata 93E3 -fillradix hexadecimal /main/ram/data(7)
mem load -filltype value -filldata 0012 -fillradix hexadecimal /main/ram/data(8)
mem load -filltype value -filldata 18CF -fillradix hexadecimal /main/ram/data(9)
mem load -filltype value -filldata 0012 -fillradix hexadecimal /main/ram/data(10)
mem load -filltype value -filldata F100 -fillradix hexadecimal /main/ram/data(11)
mem load -filltype value -filldata 0604 -fillradix hexadecimal /main/ram/data(12)
mem load -filltype value -filldata F003 -fillradix hexadecimal /main/ram/data(13)
mem load -filltype value -filldata 020F -fillradix hexadecimal /main/ram/data(14)
mem load -filltype value -filldata A000 -fillradix hexadecimal /main/ram/data(15)